NCMB.xcodeproj/project.pbxproj, NCMB/network/NCMBSignatureCalculator.swift
初めまして、よろしくお願いします。
ビルドエラーと警告の修正
1. calculateSignature() ビルドエラー修正([commit](https://github.com/NIFCloud-mbaas/ncmb_swift/commit/e0d736712709cd03e707c9773165f1edf4bb83b1))([画像](https://user-images.githubusercontent.com/45647069/56683498-a2c92000-6708-11e9-8ee2-bf13e2e7df33.png))
1. NCMBTests.swift 参照エラー修正([commit](https://github.com/NIFCloud-mbaas/ncmb_swift/commit/c9dfb615c97d15fc4ee06ba3cfd5c1cfaf4a62aa))([画像](https://user-images.githubusercontent.com/45647069/56683642-eae84280-6708-11e9-97d6-af903c5a7241.png))
1. Bundle に info.plist が含まれる警告を修正([commit](https://github.com/NIFCloud-mbaas/ncmb_swift/commit/56b9c188afe98eca84ae4e93b5f307b1c61ae34a))([画像](https://user-images.githubusercontent.com/45647069/56683995-b9bc4200-6709-11e9-8b7d-aa29905cad04.png))
- 環境
- Xcode 10.2.1
=> Fix build problem

FORDEVELOPER.md
=> SDK開発者向け資料の追加

NCMB.xcodeproj/project.pbxproj, NCMB/fieldtype/NCMBAddRelationOperator.swift, NCMB/fieldtype/NCMBFieldTypeConverter.swift, NCMB/fieldtype/NCMBPointer.swift, NCMBTests/fieldtype/NCMBAddRelationOperatorTests.swift, NCMBTests/fieldtype/NCMBFieldTypeConverterTests.swift, NCMBTests/fieldtype/NCMBPointerTests.swift
- AddRelationOperator を追加
- NCMBPointer に Equatable を実装
=> #3 add AddRelationOperator

NCMB.xcodeproj/project.pbxproj, NCMB/fieldtype/NCMBFieldTypeConverter.swift, NCMB/fieldtype/NCMBRemoveRelationOperator.swift, NCMBTests/fieldtype/NCMBFieldTypeConverterTests.swift, NCMBTests/fieldtype/NCMBRemoveRelationOperatorTests.swift
- Added RemoveRelationOperator.
=> #3 add RemoveRelationOperator

README.md
=> #3 Feature/fix readme

NCMB/fieldtype/NCMBPointer.swift, NCMBTests/fieldtype/NCMBPointerTests.swift
- added Pointer initializer #19
=> #19 added pointer initializer

NCMB/fieldtype/NCMBACL.swift, NCMBTests/component/NCMBBaseTests.swift, NCMBTests/fieldtype/NCMBACLTests.swift
=> #22 fix NCMBACL convert to json

NCMB/component/NCMBBase.swift, NCMBTests/component/NCMBBaseTests.swift
=> #29 NCMBBaseにDescriptionPropertyを追加

NCMB/fieldtype/NCMBACL.swift, NCMBTests/fieldtype/NCMBACLTests.swift
=> NCMBACLのdescriptionを追加

NCMB/NCMB.swift, NCMB/NCMBFile.swift, NCMB/NCMBInstallation.swift, NCMB/NCMBObject.swift, NCMB/NCMBPush.swift, NCMB/NCMBQuery.swift, NCMB/NCMBRole.swift, NCMB/NCMBScript.swift, NCMB/NCMBUser.swift, NCMB/component/NCMBBase.swift, NCMB/fieldtype/NCMBAddOperator.swift, NCMB/fieldtype/NCMBAddRelationOperator.swift, NCMB/fieldtype/NCMBAddUniqueOperator.swift, NCMB/fieldtype/NCMBDateField.swift, NCMB/fieldtype/NCMBGeoPoint.swift, NCMB/fieldtype/NCMBIncrementOperator.swift, NCMB/fieldtype/NCMBPointer.swift, NCMB/fieldtype/NCMBRelation.swift, NCMB/fieldtype/NCMBRemoveOperator.swift, NCMB/fieldtype/NCMBRemoveRelationOperator.swift, NCMB/user/NCMBFacebookParameters.swift, NCMB/user/NCMBGoogleParameters.swift, NCMB/user/NCMBTwitterParameters.swift, NCMBTests/helper/MockLocalFileManager.swift, NCMBTests/helper/MockRequestExecutor.swift
=> init()ドキュメントコメント変更

NCMB/NCMBScript.swift, NCMB/network/NCMBRequest.swift, NCMB/service/NCMBScriptService.swift, NCMBTests/NCMBScriptTests.swift, NCMBTests/network/NCMBRequestTests.swift, NCMBTests/service/NCMBScriptServiceTests.swift, README.md
=> fix script request

README.md
=> READMEログアウト例文不備修正

NCMB/NCMBPush.swift, NCMB/NCMBQuery.swift, NCMBTests/NCMBPushTests.swift, NCMBTests/NCMBQueryTests.swift
=> プッシュ通知　絞り込み配信登録機能の追加

README.md
- Fixed #46 
- README更新のみ
- 動作検証済み
=> プッシュ通知の絞り込み配信登録サンプルをREADMEに追加

NCMB/network/NCMBRequest.swift, NCMBTests/NCMBUserTests.swift
* ユーザ登録
```
UserName: abc+aa
Password: abc+aa
```
* ユーザログイン
```swift
// ユーザー名とパスワードでログイン
NCMBUser.logInInBackground(userName: "abc+aa", password: "abc+aa", callback: { result in
switch result {
case .success:
// ログインに成功した場合の処理
print("ログインに成功しました")
case let .failure(error):
// ログインに失敗した場合の処理
print("ログインに失敗しました: \(error)")
}
})
```
The result: 
``ログインに成功しました``
- Fixed #50 
=> Issue #50: add percent encode for plus character.

NCMB/NCMBUser.swift, NCMBTests/NCMBUserTests.swift
=> Issue #53: 第三者の会員情報を登録できない

NCMB.xcodeproj/project.pbxproj, NCMB/NCMBUser.swift, NCMB/user/NCMBAppleParameters.swift, NCMB/user/NCMBSNSType.swift, NCMBTests/NCMBUserTests.swift, NCMBTests/user/NCMBAppleParametersTests.swift
- Fixed #57 
Implement sign in with apple id.
=> issue #57 Implement signin with apple id

.gitignore, README.md, generate_reference.sh
=> リファレンス生成用シェルの追加

NCMB/NCMBUser.swift
NCMBUser.swift内のSignWithAppleTokenのコメント修正
=> fix comment in NCMBUser.swift

NCMB.podspec, NCMB/NCMB.swift, NCMBTests/NCMBInstallationTests.swift, NCMBTests/network/NCMBRequestTests.swift, README.md
=> Release prepare v1.1.1

NCMBTests/NCMBInstallationTests.swift, NCMBTests/NCMBObjectTests.swift, NCMBTests/NCMBUserTests.swift
=> Fix #43: Update createDate var name in tests

NCMB.xcodeproj/xcshareddata/xcschemes/NCMB.xcscheme, NCMB.xcodeproj/xcshareddata/xcschemes/NCMBTests.xcscheme
=> edit scheme of NCMBTests

.github/workflows/swift.yml
=> add swift.yml

NCMB/NCMBUser.swift, NCMBTests/NCMBUserTests.swift
=> issues #73: fix error authenticationErrorByHeaderIncorrect

NCMB.podspec
- Fixed #86 
❯ pod spec lint
-> NCMB (1.1.2)
- NOTE  | xcodebuild:  note: Using new build system
- NOTE  | [iOS] xcodebuild:  note: Planning build
- NOTE  | [iOS] xcodebuild:  note: Constructing build description
- NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')
Analyzed 1 podspec.
NCMB.podspec passed validation.
=> fix: podspec

NCMB.podspec, NCMB.xcodeproj/project.pbxproj
=> test swift 5.0

NCMB/NCMBQuery.swift, NCMBTests/NCMBQueryTests.swift
=> issue 4: add condition search.

.github/workflows/reference.yml
- developブランチへpushが行われたらGithub Action上でリファレンスを生成、置き換えを行いcommitします
- forkしたPJにて動作確認を行っています
- https://github.com/tanaka-kokoro/ncmb_swift
- 同じreference.ymlをmaster,developに追加してあります
- リファレンスを書き換えたp-r:https://github.com/tanaka-kokoro/ncmb_swift/pull/4 上で、Actionsの結果としてdocsファイルの置き換えが行われています
- コミット：https://github.com/tanaka-kokoro/ncmb_swift/pull/4/commits/156c1ebb474502b0b53c50d01c58eb2c1b103472
-  ![image](https://user-images.githubusercontent.com/114896458/194263200-1f608d89-c4d6-4424-8cb3-4eaab035f168.png)
- …
=> リファレンス生成・置換の自動化

NCMB/NCMB.swift, NCMB/NCMBInstallation.swift, NCMBTests/NCMBInstallationTests.swift
=> 端末情報installationのDeviceType設定を更新 

.github/workflows/reference.yml
=> #121 の再テスト

.github/workflows/swift.yml, NCMB/NCMBUser.swift, NCMB/error/NCMBInvalidRequestError.swift, NCMB/service/NCMBLoginService.swift, NCMBTests/NCMBUserTests.swift, NCMBTests/service/NCMBLoginServiceTests.swift
=> POSTメソッドでの会員ログインを実装

.github/workflows/swift.yml
=> ワークフローのxcodeバージョンを修正

.github/workflows/swift.yml, NCMBTests/NCMBObjectTests.swift
- Fixed 自動テストが失敗しているため、修正します
-  Update timeout for test cases in NCMBObject and Test xcode version
=> githubCI 上の自動テスト修正

README.md
=> iOS17を対応環境追加
